// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqsgwbqomjkxcvuehutd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxc2d3YnFvbWpreGN2dWVodXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODgyNzAsImV4cCI6MjA2NjE2NDI3MH0.9Aq-fX0hQ9FqhVZDeVQsi0Hs-K6yMhu3QQatZntrBVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);